version: '3.1'

services:

  db:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: aori143
    ports:
      - "5432:5432"
